[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  base = "/" # or the folder where your Next.js app is located, like "/app" or "/frontend"
  publish = ".next"
  command = "npm run build && npm run export"
